### PR TITLE
fix Source error m3u8 hls video

### PR DESCRIPTION
**Pull request by TruongAnim**
- Because inferContentTypeForExtension take the extention only (m3u8, mp4, etc) -> we should get extention from lastPathSegment and put to it.

### CODE REVIEW

**Comment by nateshmbhat** [comment]
any updates on this ?

**Comment by nateshmbhat** [comment]
Any reason to close this PR? Will these changes be merged and  released?

**Comment by TruongAnim** [comment]
With this code:
val fileExt = lastPathSegment.substringAfterLast('.', "")
type = Util.inferContentTypeForExtension(fileExt)
My project work fine now.

**Comment by TruongAnim** [comment]
> Any reason to close this PR? Will these changes be merged and released?

I just want to just the "m3u8 won't work" issue.
But Now I update other things to make it fit my project. So no need to merge that.

**Pull request closed without merging**
